import { ResultsContext } from "@/components/results-context";
import { useEffect, useState } from "react";
import { ScrollScrub } from "@/components/scroll-scrub/scroll-scrub";
import { scrollScrubScenes, scrollScrubTheme } from "@/scroll-scrub-scenes";
const whatsapp="https://wa.me/5514996581938?text=Olá%2C%20Talita!%20Vi%20seu%20site%20e%20gostaria%20de%20agendar%20um%20atendimento.";
const instagram="https://www.instagram.com/talitavieira08/";
function Arrow(){return <span aria-hidden="true">↗</span>;}
export default function App(){
 const[loaded,setLoaded]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>setLoaded(true),1650);return()=>window.clearTimeout(timer)},[]);
 return <main>
  <div className={loaded?"loader loader--done":"loader"} aria-hidden="true"><div className="loader__mark">TV</div><div className="loader__numbers"><span>00</span><span>37</span><span>74</span><span>100</span></div></div>
  <header className="site-nav"><a className="brand" href="#inicio" aria-label="Talita Vieira, início">Talita<span>Vieira</span></a><nav className="nav-links" aria-label="Navegação principal"><a href="#tratamentos">Tratamentos</a><a href="#filosofia">Filosofia</a><a href="#resultados">Resultados</a><a href="#talita">Talita</a></nav><a className="nav-book" href={whatsapp} target="_blank" rel="noreferrer">Agendar <Arrow/></a></header>
  <section id="inicio" className="hero-shell"><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme}/><a className="hero-cta" href={whatsapp} target="_blank" rel="noreferrer"><span>Agendar atendimento</span><b><Arrow/></b></a><div className="scroll-line" aria-hidden="true"><span/></div></section>
  <section id="filosofia" className="manifesto"><p className="micro">Cuidado personalizado</p><h2>CUIDADO.<br/><i>PRESENÇA.</i><br/>PRECISÃO.</h2><div className="manifesto-copy"><p>Cada atendimento começa com escuta e avaliação. O protocolo é pensado a partir do que você busca, respeitando seu momento e sua pele.</p><a href={whatsapp} target="_blank" rel="noreferrer">Conversar com Talita <Arrow/></a></div><div className="orbit" aria-hidden="true"><span>7+</span><small>anos de experiência</small></div></section>
  <section className="specialties"><div className="specialties-title"><p>Especialidades</p><h2>Toque técnico.<br/>Cuidado <i>humano.</i></h2></div><figure className="specialties-image specialties-image--face"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} src="/assets/generated/facial-v2.webp" alt="Cuidado facial em ambiente sereno"/><figcaption>Estética facial · imagem ilustrativa</figcaption></figure><ol><li><span>01</span><h3>Massagens e drenagens</h3><p>Atendimentos voltados ao relaxamento, bem-estar e cuidado corporal.</p></li><li><span>02</span><h3>Limpeza de pele</h3><p>Cuidado facial realizado de forma atenta e personalizada.</p></li><li><span>03</span><h3>Tratamentos corporais</h3><p>Protocolos para gordura localizada, flacidez e celulite.</p></li></ol><figure className="specialties-image specialties-image--body"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} src="/assets/generated/massage-v2.webp" alt="Massagem corporal com toque profissional"/><figcaption>Massagens · imagem ilustrativa</figcaption></figure></section>
  <section id="tratamentos" className="treatments"><header><h2>EXPLORE<br/><i>os tratamentos</i></h2><p>Serviços apresentados pela Talita em seu perfil profissional.</p></header><div className="treatments-stage"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} className="treatments-main" src="/assets/generated/massage-v2.webp" alt="Tratamento corporal em ambiente profissional"/><div className="treatment-list">{["Massagens","Drenagem","Limpeza de pele","Clareamentos","Gordura localizada","Flacidez e celulite"].map((item,i)=><a key={item} href={whatsapp} target="_blank" rel="noreferrer"><span>0{i+1}</span>{item}<Arrow/></a>)}</div><p className="vertical-note">FACIAL · CORPORAL · PERSONALIZADO</p></div></section>
  <section className="approach"><div className="approach-photo"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} src="/assets/generated/facial-v2.webp" alt="Cuidado facial em ambiente profissional"/><span>Atendimento personalizado</span></div><div className="approach-copy"><p className="micro">Abordagem</p><h2>ENTENDER<br/>ANTES DE<br/><i>CUIDAR.</i></h2><p>Talita combina avaliação, conversa e escolhas de atendimento para criar um caminho coerente com cada pessoa.</p><ol><li>Conversa inicial</li><li>Avaliação do objetivo</li><li>Tratamento personalizado</li></ol></div></section>
  <section className="laser"><div><p>Atendimento especial</p><h2>LASER<br/><i>DAY</i></h2></div><div className="laser-copy"><p>Depilação a laser, clareamentos e tratamento para vasinhos aparecem em datas especiais divulgadas pela Talita.</p><strong>Consulte a próxima data pelo WhatsApp.</strong><a href={whatsapp} target="_blank" rel="noreferrer">Consultar agenda <Arrow/></a></div></section>
  <ResultsContext/>
  <section id="talita" className="about"><div className="about-portrait"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} src="/assets/resultados/talita-retrato.webp" alt="Talita Vieira"/><span>Talita Vieira</span></div><div className="about-copy"><p className="micro">A profissional</p><h2>UM CUIDADO<br/>QUE TEM<br/><i>NOME.</i></h2><p>Talita Vieira atua em Ibirarema, SP. É especialista em massagens, realiza limpeza de pele e tratamentos personalizados, com mais de sete anos de experiência.</p><a href={instagram} target="_blank" rel="noreferrer">Conhecer o Instagram <Arrow/></a></div></section>
  <section className="insta"><div className="insta-heading"><p>@talitavieira08</p><h2>ACOMPANHE<br/>O TRABALHO</h2><a href={instagram} target="_blank" rel="noreferrer" aria-label="Abrir Instagram"><Arrow/></a></div></section>
  <footer><div className="footer-image"><img onError={(event)=>{event.currentTarget.style.visibility="hidden";event.currentTarget.parentElement?.setAttribute("data-media-unavailable","true")}} src="/assets/generated/cover-v2.webp" alt="Textura editorial em tons de vinho"/></div><div className="footer-call"><p>Ibirarema · SP</p><h2>SEU MOMENTO<br/>DE CUIDADO.</h2><a href={whatsapp} target="_blank" rel="noreferrer">Falar no WhatsApp <Arrow/></a></div><div className="footer-bottom"><a className="brand brand--footer" href="#inicio">Talita<span>Vieira</span></a><nav><a href="#tratamentos">Tratamentos</a><a href="#resultados">Resultados</a><a href={instagram} target="_blank" rel="noreferrer">Instagram</a><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a></nav><address>Ibirarema, São Paulo<br/>(14) 99658-1938</address><small>© 2026 Talita Vieira</small></div></footer>
 </main>
}
